    import EstadosYMunicipios from '../models/EstadosYmunicipios.js';

        const estadosYMunicipiosData = {
        "Aguascalientes": [
        "Aguascalientes", "Asientos", "Calvillo", "Cosío", "El Llano", 
        "Jesús María", "Pabellón de Arteaga", "Rincón de Romos", "San Francisco de los Romo", 
        , "Tepezalá", "Villa García", "Villa Hidalgo", "San José de Gracia", "San Nicolás de los Arroyos",
        "San Pedro de los Frutos", "San Juan de los Morros", "San Antonio de los Altos", "San Pedro de los Altos",
        , "San Pedro de los Morros", "San Pedro de los Teques",

    ],
    "Baja California": [
        "Ensenada", "Mexicali", "Playas de Rosarito", "Tecate", "Tijuana", "San Quintín"
    ],
    "Baja California Sur": [
        "Comondú", "La Paz", "Loreto", "Los Cabos", "Mulegé"
    ],
    "Campeche": [
        "Calakmul", "Calkiní", "Campeche", "Candelaria", "Carmen", "Champotón", 
        "Escárcega", "Hecelchakán", "Hopelchén", "Palizada", "Tenabo", "Seybaplaya", "Dzitbalché"
    ],
    "Chiapas": [
        "Acacoyagua", "Acala", "Acapetahua", "Aldama", "Altamirano", "Amatán", "Amatenango de la Frontera", 
        "Amatenango del Valle", "Ángel Albino Corzo", "Arriaga", "Bejucal de Ocampo", "Bella Vista", 
        "Berriozábal", "Bochil", "Cacahoatán", "Catazajá", "Chalchihuitán", "Chamula", "Chanal", 
        "Chapultenango", "Chenalhó", "Chiapa de Corzo", "Chiapilla", "Chicoasén", "Chicomuselo", 
        "Chilón", "Cintalapa", "Coapilla", "Comitán de Domínguez", "Copainalá", "El Bosque", 
        "El Porvenir", "Escuintla", "Francisco León", "Frontera Comalapa", "Frontera Hidalgo", 
        "Huehuetán", "Huitiupán", "Huixtán", "Huixtla", "Ixhuatán", "Ixtacomitán", "Ixtapa", 
        "Ixtapangajoya", "Jiquipilas", "Jitotol", "Juárez", "La Concordia", "La Grandeza", 
        "La Independencia", "La Libertad", "La Trinitaria", "Larráinzar", "Las Margaritas", 
        "Las Rosas", "Mapastepec", "Maravilla Tenejapa", "Marqués de Comillas", "Mazapa de Madero", 
        "Mazatán", "Metapa", "Mitontic", "Montecristo de Guerrero", "Motozintla", "Nicolás Ruíz", 
        "Ocosingo", "Ocotepec", "Ocozocoautla de Espinosa", "Ostuacán", "Osumacinta", "Oxchuc", 
        "Palenque", "Pantelhó", "Pantepec", "Pichucalco", "Pijijiapan", "Pueblo Nuevo Solistahuacán", 
        "Rayón", "Reforma", "Sabanilla", "Salto de Agua", "San Andrés Duraznal", "San Cristóbal de las Casas", 
        "San Fernando", "San Juan Cancuc", "San Lucas", "Santiago el Pinar", "Siltepec", "Simojovel", 
        "Sitalá", "Socoltenango", "Solosuchiapa", "Soyaló", "Suchiapa", "Suchiate", "Sunuapa", "Tapachula", 
        "Tapalapa", "Tapilula", "Tecpatán", "Tenejapa", "Teopisca", "Tila", "Tonalá", "Totolapa", 
        "Tumbalá", "Tuxtla Chico", "Tuxtla Gutiérrez", "Tuzantán", "Tzimol", "Unión Juárez", 
        "Venustiano Carranza", "Villa Comaltitlán", "Villa Corzo", "Villaflores", "Yajalón", "Zinacantán",
        "Emiliano Zapata", "Mezcalapa", "Capitán Luis Ángel Vidal", "Rincón Chamula San Pedro", "Honduras de la Sierra"
    ],
    "Chihuahua": [
    "Ahumada", "Aldama", "Allende", "Aquiles Serdán", "Ascensión", "Bachíniva", "Balleza", 
    "Batopilas de Manuel Gómez Morín", "Bocoyna", "Buenaventura", "Camargo", "Carichí", "Casas Grandes", 
    "Coronado", "Coyame del Sotol", "Cuauhtémoc", "Cusihuiriachi", "Chihuahua", "Chínipas", "Delicias", 
    "Dr. Belisario Domínguez", "El Tule", "Galeana", "Gómez Farías", "Gran Morelos", "Guachochi", 
    "Guadalupe", "Guadalupe y Calvo", "Guazapares", "Guerrero", "Hidalgo del Parral", "Huejotitán", 
    "Ignacio Zaragoza", "Janos", "Jiménez", "Juárez", "Julimes", "La Cruz", "López", "Madera", 
    "Maguarichi", "Manuel Benavides", "Matachí", "Matamoros", "Meoqui", "Morelos", "Moris", 
    "Namiquipa", "Nonoava", "Nuevo Casas Grandes", "Ocampo", "Ojinaga", "Praxedis G. Guerrero", 
    "Riva Palacio", "Rosales", "Rosario", "San Francisco de Borja", "San Francisco de Conchos", 
    "San Francisco del Oro", "Santa Bárbara", "Santa Isabel", "Satevó", "Saucillo", "Temósachic", 
    "Urique", "Uruachi", "Valle de Zaragoza"
    ],
    "Ciudad de México": [
        "Álvaro Obregón", "Azcapotzalco", "Benito Juárez", "Coyoacán", "Cuajimalpa de Morelos", 
        "Cuauhtémoc", "Gustavo A. Madero", "Iztacalco", "Iztapalapa", "La Magdalena Contreras", 
        "Miguel Hidalgo", "Milpa Alta", "Tlalpan", "Tláhuac", "Venustiano Carranza", "Xochimilco"
    ],
    "Coahuila": [
        "Abasolo", "Acuña", "Allende", "Arteaga", "Candela", "Castaños", "Cuatro Ciénegas", 
        "Escobedo", "Francisco I. Madero", "Frontera", "General Cepeda", "Guerrero", "Hidalgo", 
        "Jiménez", "Juárez", "Lamadrid", "Matamoros", "Monclova", "Morelos", "Múzquiz", 
        "Nadadores", "Nava", "Ocampo", "Parras", "Piedras Negras", "Progreso", "Ramos Arizpe", 
        "Sabinas", "Sacramento", "Saltillo", "San Buenaventura", "San Juan de Sabinas", 
        "San Pedro", "Sierra Mojada", "Torreón", "Viesca", "Villa Unión", "Zaragoza"
    ],
    "Colima": [
        "Armería", "Colima", "Comala", "Coquimatlán", "Cuauhtémoc", "Ixtlahuacán", 
        "Manzanillo", "Minatitlán", "Tecomán", "Villa de Álvarez"
    ],
    "Durango": [
        "Canatlán", "Canelas", "Coneto de Comonfort", "Cuencamé", "Durango", "El Oro", 
        "Gómez Palacio", "General Simón Bolívar", "Guadalupe Victoria", "Guanaceví", 
        "Hidalgo", "Indé", "Lerdo", "Mapimí", "Mezquital", "Nazas", "Nombre de Dios", 
        "Nuevo Ideal", "Ocampo", "Otáez", "Pánuco de Coronado", "Peñón Blanco", 
        "Poanas", "Pueblo Nuevo", "Rodeo", "San Bernardo", "San Dimas", "San Juan de Guadalupe", 
        "San Juan del Río", "San Luis del Cordero", "San Pedro del Gallo", "Santa Clara", 
        "Santiago Papasquiaro", "Súchil", "Tamazula", "Tepehuanes", "Tlahualilo", "Topia", "Vicente Guerrero"
    ],
    "Guanajuato": [
        "Abasolo", "Acámbaro", "Apaseo el Alto", "Apaseo el Grande", "Atarjea", "Celaya",
        "Comonfort", "Coroneo", "Cortazar", "Cuerámaro", "Doctor Mora", "Dolores Hidalgo",
        "Guanajuato", "Huanímaro", "Irapuato", "Jaral del Progreso", "Jerécuaro", "León",
        "Moroleón", "Ocampo", "Pénjamo", "Purísima del Rincón", "Romita", "Salamanca",
        "Salvatierra", "San Diego de la Unión", "San Felipe", "San Francisco del Rincón",
        "San José Iturbide", "San Luis de la Paz", "San Miguel de Allende", "Santa Catarina",
        "Santa Cruz de Juventino Rosas", "Santiago Maravatío", "Silao", "Tarandacuao",
        "Tarimoro", "Tierra Blanca", "Uriangato", "Valle de Santiago", "Victoria",
        "Villagrán", "Xichú", "Yuriria"
    ],
    "Guerrero": [
        "Acapulco de Juárez", "Ahuacuotzingo", "Ajuchitlán del Progreso", "Alcozauca de Guerrero",
        "Alpoyeca", "Apango", "Atlixtac", "Ayutla de los Libres", "Azoyú", "Coahuayutla de José María Izazaga",
        "Cocula", "Copala", "Coyuca de Benítez", "Cuajinicuilapa", "Cualác", "Cutzamala de Pinzón",
        "Chilapa de Álvarez", "Chilpancingo de los Bravo", "Cochoapa el Grande", "Cocula", "Cuetzala del Progreso",
        "Eduardo Neri", "Florencio Villarreal", "General Heliodoro Castillo", "General Juan R. Escudero",
        "Huamuxtitlán", "Huitzuco de los Figueroa", "Iguala de la Independencia", "Igualapa", "Iliatenco",
        "Juchitán", "La Campana", "La Unión de Isidoro Montes de Oca", "Leonardo Bravo", "Malinaltepec",
        "Marquelia", "Mártir de Cuilapan", "Metlatónoc", "Mochitlán", "Olinalá", "Ometepec",
        "Pedro Ascencio de Alquisiras", "Petatlán", "Pungarabato", "Quechultenango", "San Luis Acatlán",
        "San Marcos", "San Miguel Totolapan", "San Pablo Coatlan", "San Pedro Huamelula",
        "San Jerónimo de Juárez", "San Vicente de Benjamín Hill", "Santa Bárbara", "Santa Cruz del Rincón",
        "Santa María Tonameca", "Tecpan de Galeana", "Teloloapan", "Tepecoacuilco de Trujano",
        "Tepecuacuilco", "Tetipac", "Tixtla de Guerrero", "Tlacoachistlahuaca", "Tlacoapa",
        "Tlalixtaquilla de Maldonado", "Tlapa de Comonfort", "Tlalchapa", "Tlapehuala", "Tlalchichilpan",
        "Tlazazalca", "Tocumbo", "Tlalchapa", "Xalpatlahuac", "Xochihuehuetlán", "Zitlala",
        "Zihuatanejo de Azueta", "Zitácuaro", "Zumpango del Río", "Zumpil", "Zumpango"
    ],
    "Hidalgo": [
        "Acatlán", "Actopan", "Agua Blanca de Iturbide", "Ajacuba", "Alfajayucan", "Apan",
        "Atitalaquia", "Atlapexco", "Atotonilco de Tula", "Calnali", "Cardonal", "Cuautepec de Hinojosa",
        "Chapantongo", "Chilcuautla", "Cuautepec", "Epazoyucan", "Francisco I. Madero", "Huasca de Ocampo",
        "Huejutla de Reyes", "Huichapan", "Ixmiquilpan", "Jacala de Ledezma", "Jaltocán", "Juárez Hidalgo",
        "La Misión", "Landa de Matamoros", "Mineral de la Reforma", "Mixquiahuala de Juárez",
        "Mizquiahuala de Juárez", "Nicolás Flores", "Nopala de Villagrán", "Omitlán de Juárez",
        "Pachuca de Soto", "Progreso de Obregón", "San Agustín Tlaxiaca", "San Bartolo Tutotepec",
        "San Felipe Orizatlán", "San Salvador", "San Salvador", "San Vicente", "Santiago de Anaya",
        "Santiago Tulantepec de Lugo Guerrero", "Singuilucan", "Tizayuca", "Tlaxcoapan", "Tula de Allende",
        "Tulancingo de Bravo", "Xochiatipan", "Yahualica", "Zacualtipán de Ángeles", "Zimapán"
    ],
    "Jalisco": [
        "Acatic", "Acatlán de Juárez", "Ahualulco de Mercado", "Amacueca", "Amatitlán", "Arandas",
        "Atemajac de Brizuela", "Atengo", "Atotonilco el Alto", "Ayotlán", "Bolaños", "Cabo Corrientes",
        "Casimiro Castillo", "Cihuatlán", "Cocula", "Colotlán", "Concepción de Buenos Aires",
        "Cuautitlán de García Barragán", "Degollado", "El Arenal", "El Grullo", "El Limón",
        "El Salto", "Encarnación de Díaz", "Guachinango", "Guadalajara", "Hostotipaquillo",
        "Huejúcar", "Ixtlahuacán de los Membrillos", "Ixtlahuacán del Río", "Jalostotitlán",
        "Jamay", "Jesús María", "Jilotlán de los Dolores", "Jocotepec", "Juanacatlán", "La Huerta",
        "La Manzanilla de la Paz", "La Resolana", "Lagos de Moreno", "Magdalena", "Mazamitla",
        "Mexticacán", "Mezquitic", "Mixtlán", "Ocotlán", "Pihuamo", "Poncitlán", "Puerto Vallarta",
        "San Cristóbal de la Barranca", "San Diego de Alejandría", "San Gabriel", "San Juan de los Arcos",
        "San Juanito de Escobedo", "San Julián", "San Martín de Bolaños", "San Martín Hidalgo",
        "San Miguel el Alto", "San Pedro Tlaquepaque", "San Sebastián del Oeste", "Santa María de los Ángeles",
        "Sayula", "Tala", "Tamazula de Gordiano", "Tapalpa", "Tecalitlán", "Teocaltiche",
        "Teocuitatlán de Corona", "Tequila", "Tolimán", "Tonalá", "Tonaya", "Totatiche",
        "Tuxcacuesco", "Tuxcueca", "Unión de San Antonio", "Valle de Juárez", "Villa Corona",
        "Villa Guerrero", "Villa Hidalgo", "Yahualica de González Gallo", "Zacoalco de Torres",
        "Zapotiltic", "Zapotlanejo", "Zapotlán el Grande", "Zapotlanejo", "Zapotlán del Rey",
        "Zapotlán de Juárez", "Zapotlán de los Dolores", "Zapotlán de la Frontera", "Zapotlán de los Reyes",
        "Zapotlán de los Caballeros", "Zapotlán de las Salinas", "Zapotlán de la Sierra",
        "Zapotlán de los Tejas", "Zapotlán de los Tres Reyes", "Zapotlán de los Dos Ríos",
    ],
    "Nueva León": [
        "Abasolo", "Agualeguas", "Allende", "Anáhuac", "Apodaca", "Aramberri", "Cadereyta Jiménez",
        "Cerralvo", "China", "Ciénega de Flores", "Doctor Arroyo", "Doctor González", "El Carmen",
        "El Cercado", "El Escobedo", "El Salto", "García", "General Bravo", "General Escobedo",
        "General Terán", "General Zaragoza", "Guadalupe", "Hualahuises", "Iturbide", "Juárez",
        "Lampazos de Naranjo", "Linares", "Marín", "Melchor Múzquiz", "Mier y Noriega",
        "Monterrey", "Montemorelos", "Parás", "Pesquería", "Rayones", "Sabinas Hidalgo",
        "Salinas Victoria", "San Nicolás de los Garza", "San Pedro Garza García", "Santa Catarina",
        "Santiago", "Vallecillo", "Villaldama", "Villa de García", "Villa de Santiago",
        "Villa de Juárez", "Villa de la Paz", "Villa de la Independencia", "Villa de la Libertad",
        "Villa de la Revolución", "Villa de la Victoria", "Villa de la Esperanza", "Villa de la Paz",
        "Villa de la Libertad",
    ],
    "Estado de México": [
    "Acambay", "Acolman", "Aculco", "Almoloya de Alquisiras", "Almoloya de Juárez", 
    "Almoloya del Río", "Amanalco", "Amatepec", "Amecameca", "Apaxco", "Atenco", 
    "Atizapán", "Atizapán de Zaragoza", "Atlacomulco", "Atlautla", "Axapusco", 
    "Ayapango", "Calimaya", "Capulhuac", "Chalco", "Chapa de Mota", "Chapultepec", 
    "Chiautla", "Chicoloapan", "Chiconcuac", "Chimalhuacán", "Coacalco de Berriozábal", 
    "Coatepec Harinas", "Cocotitlán", "Coyotepec", "Cuautitlán", "Cuautitlán Izcalli", 
    "Donato Guerra", "Ecatepec de Morelos", "Ecatzingo", "El Oro", "Huehuetoca", 
    "Hueypoxtla", "Huixquilucan", "Isidro Fabela", "Ixtapaluca", "Ixtapan de la Sal", 
    "Ixtapan del Oro", "Ixtlahuaca", "Jaltenco", "Jilotepec", "Jilotzingo", 
    "Jiquipilco", "Jocotitlán", "Joquicingo", "Juchitepec", "La Paz", "Lerma", 
    "Luvianos", "Malinalco", "Melchor Ocampo", "Metepec", "Mexicaltzingo", 
    "Morelos", "Naucalpan de Juárez", "Nextlalpan", "Nezahualcóyotl", "Nicolás Romero", 
    "Nopaltepec", "Ocoyoacac", "Ocuilan", "Otumba", "Otzoloapan", "Otzolotepec", 
    "Ozumba", "Papalotla", "Polotitlán", "Rayón", "San Antonio la Isla", 
    "San Felipe del Progreso", "San José del Rincón", "San Martín de las Pirámides", 
    "San Mateo Atenco", "San Simón de Guerrero", "Santo Tomás", "Soyaniquilpan de Juárez", 
    "Sultepec", "Tecámac", "Tejupilco", "Temamatla", "Temascalapa", "Temascalcingo", 
    "Temascaltepec", "Temoaya", "Tenancingo", "Tenango del Aire", "Tenango del Valle", 
    "Teoloyucan", "Teotihuacán", "Tepetlaoxtoc", "Tepetlixpa", "Tepotzotlán", 
    "Tequixquiac", "Texcaltitlán", "Texcalyacac", "Texcoco", "Tezoyuca", 
    "Tianguistenco", "Timilpan", "Tlalmanalco", "Tlalnepantla de Baz", "Tlatlaya", 
    "Toluca", "Tonatico", "Tultepec", "Tultitlán", "Valle de Bravo", 
    "Villa de Allende", "Villa del Carbón", "Villa Guerrero", "Villa Victoria", 
    "Xalatlaco", "Xonacatlán", "Zacazonapan", "Zacualpan", "Zinacantepec", 
    "Zumpahuacán", "Zumpango"
],
"Michoacán": [
    "Acuitzio", "Aguililla", "Álvaro Obregón", "Angamacutiro", "Angangueo", 
    "Apatzingán", "Aporo", "Aquila", "Ario", "Arteaga", "Briseñas", 
    "Buenavista", "Carácuaro", "Charapan", "Charo", "Chavinda", 
    "Cherán", "Chilchota", "Chinicuila", "Chucándiro", "Churintzio", 
    "Churumuco", "Coahuayana", "Coalcomán de Vázquez Pallares", "Coeneo", 
    "Contepec", "Copándaro", "Cotija", "Cuitzeo", "Ecuandureo", 
    "Epitacio Huerta", "Erongarícuaro", "Gabriel Zamora", "Hidalgo", 
    "Huandacareo", "Huaniqueo", "Huetamo", "Huiramba", "Indaparapeo", 
    "Irimbo", "Ixtlán", "Jacona", "Jiménez", "Jiquilpan", 
    "Juárez", "Jungapeo", "Lagunillas", "La Piedad", "Lázaro Cárdenas", 
    "Los Reyes", "Madero", "Maravatío", "Marcos Castellanos", "Morelia", 
    "Morelos", "Múgica", "Nahuatzen", "Nocupétaro", "Nuevo Parangaricutiro", 
    "Nuevo Urecho", "Numarán", "Ocampo", "Pajacuarán", "Panindícuaro", 
    "Paracho", "Parácuaro", "Pátzcuaro", "Penjamillo", "Peribán", 
    "Purépero", "Puruándiro", "Queréndaro", "Quiroga", "Sahuayo", 
    "Salvador Escalante", "San Lucas", "Santa Ana Maya", "Senguio", 
    "Susupuato", "Tacámbaro", "Tancítaro", "Tangamandapio", "Tangancícuaro", 
    "Tanhuato", "Taretan", "Tarímbaro", "Tepalcatepec", "Tingambato", 
    "Tingüindín", "Tiquicheo de Nicolás Romero", "Tlalpujahua", "Tlazazalca", 
    "Tocumbo", "Tumbiscatío", "Turicato", "Tuxpan", "Tuzantla", 
    "Tzintzuntzan", "Tzitzio", "Uruapan", "Venustiano Carranza", 
    "Villamar", "Vista Hermosa", "Yurécuaro", "Zacapu", "Zamora", 
    "Zináparo", "Zinapécuaro", "Ziracuaretiro", "Zitácuaro"
],
"Morelos": [
    "Amacuzac", "Atlatlahucan", "Axochiapan", "Ayala", "Coatlán del Río", 
    "Cuautla", "Cuernavaca", "Emiliano Zapata", "Huitzilac", "Jantetelco", 
    "Jiutepec", "Jojutla", "Jonacatepec", "Mazatepec", "Miacatlán", 
    "Ocuituco", "Puente de Ixtla", "Temixco", "Temoac", "Tepalcingo", 
    "Tepoztlán", "Tetecala", "Tetela del Volcán", "Tlalnepantla", 
    "Tlaltizapán", "Tlaquiltenango", "Tlayacapan", "Totolapan", "Xochitepec", 
    "Yautepec", "Yecapixtla", "Zacatepec", "Zacualpan de Amilpas"
],
"Nayarit": [
    "Acaponeta", "Ahuacatlán", "Amatlán de Cañas", "Bahía de Banderas", 
    "Compostela", "El Nayar", "Huajicori", "Ixtlán del Río", "Jala", 
    "La Yesca", "Rosamorada", "Ruíz", "San Blas", "San Pedro Lagunillas", 
    "Santa María del Oro", "Santiago Ixcuintla", "Tecuala", "Tepic", 
    "Tuxpan", "Xalisco"
],
"Oaxaca": [
    "Abejones", "Acatlán de Pérez Figueroa", "Asunción Cacalotepec", 
    "Asunción Cuyotepeji", "Asunción Ixtaltepec", "Asunción Nochixtlán", 
    "Asunción Ocotlán", "Asunción Tlacolulita", "Ayotzintepec", 
    "El Barrio de la Soledad", "Calihualá", "Candelaria Loxicha", 
    "Ciénega de Zimatlán", "Ciudad Ixtepec", "Coatecas Altas", 
    "Coicoyán de las Flores", "Concepción Buenavista", "Concepción Pápalo", 
    "Constancia del Rosario", "Cosolapa", "Cosoltepec", "Cuilápam de Guerrero", 
    "Cuyamecalco Villa de Zaragoza", "El Espinal", "Tamazulápam del Espíritu Santo", 
    "Fresnillo de Trujano", "Guadalupe de Ramírez", "Guadalupe Etla", 
    "Guelatao de Juárez", "Guevea de Humboldt", "Heroica Ciudad de Huajuapan de León", 
    "Heroica Ciudad de Tlaxiaco", "Huautepec", "Huautla de Jiménez", 
    "Ixpantepec Nieves", "Ixtlán de Juárez", "La Compañía", 
    "La Pe", "La Reforma", "Santa Cruz Itundujia", "Santa Cruz Xoxocotlán", 
    "Santa Cruz Zenzontepec", "Santa Gertrudis", "Santa Inés del Monte", 
    "Santa Lucía del Camino", "Santa María Alotepec", "Santa María Apazco", 
    "Santa María Atzompa", "Santa María Camotlán", "Santa María Chachoápam", 
    "Santa María Chilchotla", "Santa María Chimalapa", "Santa María Colotepec", 
    "Santa María Cortijo", "Santa María Coyotepec", "Santa María del Rosario", 
    "Santa María del Tule", "Santa María Ecatepec", "Santa María Guelacé", 
    "Santa María Guienagati", "Santa María Huatulco", "Santa María Huazolotitlán", 
    "Santa María Ipalapa", "Santa María Ixcatlán", "Santa María Jacatepec", 
    "Santa María Jalapa del Marqués", "Santa María Jaltianguis", 
    "Santa María la Asunción", "Santa María Lachixío", "Santa María Mixtequilla", 
    "Santa María Nativitas", "Santa María Nduayaco", "Santa María Ozolotepec", 
    "Santa María Pápalo", "Santa María Peñoles", "Santa María Petapa", 
    "Santa María Quiegolani", "Santa María Sola", "Santa María Tataltepec", 
    "Santa María Tecomavaca", "Santa María Temaxcalapa", "Santa María Temaxcaltepec", 
    "Santa María Teopoxco", "Santa María Tepantlali", "Santa María Texcatitlán", 
    "Santa María Tlahuitoltepec", "Santa María Tlalixtac", "Santa María Tonameca", 
    "Santa María Totolapilla", "Santa María Xadani", "Santa María Yalina", 
    "Santa María Yavesía", "Santa María Yolotepec", "Santa María Yosoyúa", 
    "Santa María Yucuhiti", "Santa María Zacatepec", "Santa María Zaniza", 
    "Santa María Zoquitlán", "Santiago Amoltepec", "Santiago Apoala", 
    "Santiago Apóstol", "Santiago Astata", "Santiago Atitlán", 
    "Santiago Ayuquililla", "Santiago Cacaloxtepec", "Santiago Camotlán", 
    "Santiago Chazumba", "Santiago Choápam", "Santiago Comaltepec", 
    "Santiago del Río", "Santiago Huajolotitlán", "Santiago Huauclilla", 
    "Santiago Ihuitlán Plumas", "Santiago Ixcuintepec", "Santiago Ixtayutla", 
    "Santiago Jamiltepec", "Santiago Jocotepec", "Santiago Juxtlahuaca", 
    "Santiago Lachiguiri", "Santiago Lalopa", "Santiago Laollaga", 
    "Santiago Laxopa", "Santiago Llano Grande", "Santiago Matatlán", 
    "Santiago Miltepec", "Santiago Minas", "Santiago Nacaltepec", 
    "Santiago Nejapilla", "Santiago Niltepec", "Santiago Nundiche", 
    "Santiago Nuyoó", "Santiago Pinotepa Nacional", "Santiago Suchilquitongo", 
    "Santiago Tamazola", "Santiago Tapextla", "Santiago Tenango", 
    "Santiago Tepetlapa", "Santiago Tetepec", "Santiago Texcalcingo", 
    "Santiago Textitlán", "Santiago Tilantongo", "Santiago Tillo", 
    "Santiago Tlazoyaltepec", "Santiago Xanica", "Santiago Xiacuí", 
    "Santiago Yaitepec", "Santiago Yaveo", "Santiago Yolomécatl", 
    "Santiago Yosondúa", "Santiago Yucuyachi", "Santiago Zacatepec", 
    "Santiago Zoochila", "Santo Domingo Albarradas", "Santo Domingo Armenta", 
    "Santo Domingo Chihuitán", "Santo Domingo de Morelos", "Santo Domingo Ingenio", 
    "Santo Domingo Ixcatlán", "Santo Domingo Nuxaá", "Santo Domingo Ozolotepec", 
    "Santo Domingo Petapa", "Santo Domingo Roayaga", "Santo Domingo Tehuantepec", 
    "Santo Domingo Teojomulco", "Santo Domingo Tepuxtepec", "Santo Domingo Tlatayápam", 
    "Santo Domingo Tomaltepec", "Santo Domingo Tonalá", "Santo Domingo Tonaltepec", 
    "Santo Domingo Xagacía", "Santo Domingo Yanhuitlán", "Santo Domingo Yodohino", 
    "Santo Domingo Zanatepec", "Santo Tomás Jalieza", "Santo Tomás Mazaltepec", 
    "Santo Tomás Ocotepec", "Santo Tomás Tamazulapan", "Santos Reyes Nopala", 
    "Santos Reyes Pápalo", "Santos Reyes Tepejillo", "Santos Reyes Yucuná", 
    "Silacayoápam", "Sitio de Xitlapehua", "Soledad Etla", "Villa de Tamazulápam del Progreso", 
    "Villa de Tututepec de Melchor Ocampo", "Villa de Zaachila", "Villa Díaz Ordaz", 
    "Villa Hidalgo", "Villa Sola de Vega", "Villa Talea de Castro", 
    "Villa Tejúpam de la Unión", "Yaxe", "Yogana", "Yutanduchi de Guerrero", 
    "Zapotitlán Lagunas", "Zapotitlán Palmas", "Zimatlán de Álvarez"
],
"Querétaro": [
        "Amealco de Bonfil", "Arroyo Seco", "Cadereyta de Montes", "Colón", 
        "Corregidora", "El Marqués", "Ezequiel Montes", "Huimilpan", 
        "Jalpan de Serra", "Landa de Matamoros", "Pedro Escobedo", 
        "Peñamiller", "Pinal de Amoles", "Querétaro", "San Joaquín", 
        "San Juan del Río", "Tequisquiapan", "Tolimán"
    ],
    "Quintana Roo": [
        "Bacalar", "Benito Juárez (Cancún)", "Cozumel", "Felipe Carrillo Puerto", 
        "Isla Mujeres", "José María Morelos", "Lázaro Cárdenas", "Othón P. Blanco (Chetumal)", 
        "Puerto Morelos", "Solidaridad (Playa del Carmen)", "Tulum"
    ],
    "San Luis Potosí": [
        "Ahualulco", "Alaquines", "Aquismón", "Armadillo de los Infante", 
        "Axtla de Terrazas", "Cárdenas", "Catorce", "Cedral", 
        "Cerritos", "Cerro de San Pedro", "Charcas", "Ciudad del Maíz", 
        "Ciudad Fernández", "Ciudad Valles", "Coxcatlán", "Ebano", 
        "El Naranjo", "Guadalcázar", "Huehuetlán", "Lagunillas", 
        "Matehuala", "Matlapa", "Mexquitic de Carmona", "Moctezuma", 
        "Rayón", "Rioverde", "Salinas", "San Antonio", 
        "San Ciro de Acosta", "San Luis Potosí", "San Martín Chalchicuautla", 
        "San Nicolás Tolentino", "San Vicente Tancuayalab", "Santa Catarina", 
        "Santa María del Río", "Santo Domingo", "Soledad de Graciano Sánchez", 
        "Tamasopo", "Tamazunchale", "Tampacán", "Tampamolón Corona", 
        "Tamuin", "Tancanhuitz", "Tanlajás", "Tanquián de Escobedo", 
        "Tierra Nueva", "Vanegas", "Venado", "Villa de Arista", 
        "Villa de Arriaga", "Villa de Guadalupe", "Villa de la Paz", 
        "Villa de Ramos", "Villa de Reyes", "Villa Hidalgo", "Villa Juárez", 
        "Xilitla", "Zaragoza"
    ],
    "Sinaloa": [
        "Ahome", "Angostura", "Badiraguato", "Choix", 
        "Concordia", "Cosala", "Culiacán", "El Fuerte", 
        "Elota", "Escuinapa", "Guasave", "Mazatlán", 
        "Mocorito", "Navolato", "Rosario", "Salvador Alvarado", 
        "San Ignacio", "Sinaloa"
    ],
    "Sonora": [
        "Aconchi", "Agua Prieta", "Alamos", "Altar", 
        "Arivechi", "Arizpe", "Atil", "Bacadéhuachi", 
        "Bacanora", "Bacerac", "Bacoachi", "Bácum", 
        "Banámichi", "Baviácora", "Bavispe", "Benito Juárez", 
        "Benjamín Hill", "Caborca", "Cajeme", "Cananea", 
        "Carbó", "Cucurpe", "Cumpas", "Divisaderos", 
        "Empalme", "Etchojoa", "Fronteras", "General Plutarco Elías Calles", 
        "Granados", "Guaymas", "Hermosillo", "Huachinera", 
        "Huásabas", "Huatabampo", "Huépac", "Imuris", 
        "La Colorada", "Magdalena", "Mazatán", "Moctezuma", 
        "Naco", "Nácori Chico", "Nacozari de García", "Navojoa", 
        "Nogales", "Onavas", "Opodepe", "Oquitoa", 
        "Pitiquito", "Puerto Peñasco", "Quiriego", "Rayón", 
        "Rosario", "Sahuaripa", "San Felipe de Jesús", "San Ignacio Río Muerto", 
        "San Javier", "San Luis Río Colorado", "San Miguel de Horcasitas", 
        "San Pedro de la Cueva", "Santa Ana", "Santa Cruz", 
        "Sáric", "Soyopa", "Suaqui Grande", "Tepache", 
        "Trincheras", "Tubutama", "Ures", "Villa Hidalgo", 
        "Villa Pesqueira", "Yécora"
    ],
    "Tabasco": [
        "Balancán", "Cárdenas", "Centla", "Centro (Villahermosa)", 
        "Comalcalco", "Cunduacán", "Emiliano Zapata", "Huimanguillo", 
        "Jalapa", "Jalpa de Méndez", "Jonuta", "Macuspana", 
        "Nacajuca", "Paraíso", "Tacotalpa", "Teapa", 
        "Tenosique"
    ],
    "Tamaulipas": [
        "Abasolo", "Aldama", "Altamira", "Antiguo Morelos", 
        "Burgos", "Bustamante", "Camargo", "Casas", 
        "Ciudad Madero", "Cruillas", "El Mante", "Gómez Farías", 
        "González", "Güémez", "Guerrero", "Gustavo Díaz Ordaz", 
        "Hidalgo", "Jaumave", "Jiménez", "Llera", 
        "Mainero", "Matamoros", "Méndez", "Mier", 
        "Miguel Alemán", "Miquihuana", "Nuevo Laredo", "Nuevo Morelos", 
        "Ocampo", "Padilla", "Palmillas", "Reynosa", 
        "Río Bravo", "San Carlos", "San Fernando", "San Nicolás", 
        "Soto la Marina", "Tampico", "Tula", "Valle Hermoso", 
        "Victoria", "Villagrán", "Xicoténcatl"
    ],
    "Tlaxcala": [
        "Amaxac de Guerrero", "Apetatitlán de Antonio Carvajal", "Atlangatepec", 
        "Altzayanca", "Apizaco", "Calpulalpan", "Chiautempan", "Contla de Juan Cuamatzi", 
        "Cuapiaxtla", "Cuaxomulco", "El Carmen Tequexquitla", "Emiliano Zapata", 
        "Españita", "Huamantla", "Hueyotlipan", "Ixtacuixtla de Mariano Matamoros", 
        "Ixtenco", "La Magdalena Tlaltelulco", "Lázaro Cárdenas", "Mazatecochco de José María Morelos", 
        "Nanacamilpa de Mariano Arista", "Natívitas", "Panotla", "Papalotla de Xicohténcatl", 
        "San Damián Texoloc", "San Francisco Tetlanohcan", "San Jerónimo Zacualpan", 
        "San José Teacalco", "San Juan Huactzinco", "San Lorenzo Axocomanitla", 
        "San Lucas Tecopilco", "San Pablo del Monte", "Sanctórum de Lázaro Cárdenas", 
        "Santa Ana Nopalucan", "Santa Apolonia Teacalco", "Santa Catarina Ayometla", 
        "Santa Cruz Quilehtla", "Santa Cruz Tlaxcala", "Santa Isabel Xiloxoxtla", 
        "Tenancingo", "Teolocholco", "Tepetitla de Lardizábal", "Tepeyanco", 
        "Terrenate", "Tetla de la Solidaridad", "Tetlatlahuca", "Tlaxcala", 
        "Tlaxco", "Tocatlán", "Totolac", "Tzompantepec", 
        "Xaloztoc", "Xaltocan", "Xicohtzinco", "Yauhquemehcan", 
        "Zacatelco", "Ziltlaltépec de Trinidad Sánchez Santos"
    ],
    "Veracruz": [
        "Acajete", "Acatlán", "Acayucan", "Actopan", 
        "Acula", "Acultzingo", "Agua Dulce", "Álamo Temapache", 
        "Alpatláhuac", "Alto Lucero de Gutiérrez Barrios", "Altotonga", "Alvarado", 
        "Amatitlán", "Amatlán de los Reyes", "Angel R. Cabada", "Apazapan", 
        "Aquila", "Astacinga", "Atlahuilco", "Atoyac", 
        "Atzacan", "Atzalan", "Ayahualulco", "Banderilla", 
        "Benito Juárez", "Boca del Río", "Calcahualco", "Camarón de Tejeda", 
        "Camerino Z. Mendoza", "Carlos A. Carrillo", "Carrillo Puerto", "Castillo de Teayo", 
        "Catemaco", "Cazones de Herrera", "Cerro Azul", "Chacaltianguis", 
        "Chalma", "Chiconamel", "Chiconquiaco", "Chicontepec", 
        "Chinameca", "Chinampa de Gorostiza", "Chocamán", "Chontla", 
        "Chumatlán", "Citlaltépetl", "Coacoatzintla", "Coahuitlán", 
        "Coatepec", "Coatzacoalcos", "Coatzintla", "Coetzala", 
        "Colipa", "Comapa", "Córdoba", "Cosamaloapan de Carpio", 
        "Cosautlán de Carvajal", "Coscomatepec", "Cosoleacaque", "Cotaxtla", 
        "Coxquihui", "Coyutla", "Cuichapa", "Cuitláhuac", 
        "El Higo", "Emiliano Zapata", "Espinal", "Filomeno Mata", 
        "Fortín", "Gutiérrez Zamora", "Hidalgotitlán", "Huatusco", 
        "Huayacocotla", "Hueyapan de Ocampo", "Huiloapan de Cuauhtémoc", "Ignacio de la Llave", 
        "Ilamatlán", "Isla", "Ixcatepec", "Ixhuacán de los Reyes", 
        "Ixhuatlán del Café", "Ixhuatlancillo", "Ixhuatlán del Sureste", "Ixhuatlán de Madero", 
        "Ixmatlahuacan", "Ixtaczoquitlán", "Jalacingo", "Jalcomulco", 
        "Jáltipan", "Jamapa", "Jesús Carranza", "Jilotepec", 
        "José Azueta", "Juan Rodríguez Clara", "Juchique de Ferrer", "La Antigua", 
        "La Perla", "Landero y Coss", "Las Choapas", "Las Minas", 
        "Las Vigas de Ramírez", "Lerdo de Tejada", "Los Reyes", "Magdalena", 
        "Maltrata", "Manlio Fabio Altamirano", "Mariano Escobedo", "Martínez de la Torre", 
        "Mecatlán", "Mecayapan", "Medellín", "Miahuatlán", 
        "Minatitlán", "Misantla", "Mixtla de Altamirano", "Moloacán", 
        "Nanchital", "Naolinco", "Naranjal", "Naranjos Amatlán", 
        "Nautla", "Nogales", "Oluta", "Omealca", 
        "Orizaba", "Otatitlán", "Oteapan", "Ozuluama de Mascareñas", 
        "Pajapan", "Pánuco", "Papantla", "Paso de Ovejas", 
        "Paso del Macho", "Perote", "Platón Sánchez", "Playa Vicente", 
        "Poza Rica de Hidalgo", "Pueblo Viejo", "Puente Nacional", "Rafael Delgado", 
        "Rafael Lucio", "Los Reyes", "Río Blanco", "Saltabarranca", 
        "San Andrés Tenejapan", "San Andrés Tuxtla", "San Juan Evangelista", "San Rafael", 
        "Santiago Sochiapan", "Santiago Tuxtla", "Sayula de Alemán", "Sochiapa", 
        "Soconusco", "Soledad Atzompa", "Soledad de Doblado", "Soteapan", 
        "Tamalín", "Tamiahua", "Tampico Alto", "Tancoco", 
        "Tantima", "Tantoyuca", "Tatahuicapan de Juárez", "Tatatila", 
        "Tecolutla", "Tehuipango", "Tempoal", "Tenampa", 
        "Tenochtitlán", "Teocelo", "Tepatlaxco", "Tepetlán", 
        "Tepetzintla", "Tequila", "Texcatepec", "Texhuacán", 
        "Texistepec", "Tezonapa", "Tierra Blanca", "Tihuatlán", 
        "Tlacojalpan", "Tlacolulan", "Tlacotalpan", "Tlacotepec de Mejía", 
        "Tlachichilco", "Tlalixcoyan", "Tlalnelhuayocan", "Tlapacoyan", 
        "Tlaquilpa", "Tlilapan", "Tomatlán", "Tonayán", 
        "Totutla", "Tres Valles", "Túxpam", "Tuxtilla", 
        "Ursulo Galván", "Vega de Alatorre", "Veracruz", "Villa Aldama", 
        "Xalapa", "Xico", "Xoxocotla", "Yanga", 
        "Yecuatla", "Zacualpan", "Zaragoza", "Zentla", 
        "Zongolica", "Zontecomatlán", "Zozocolco de Hidalgo"
    ],
    "Yucatán": [
        "Abalá", "Acanceh", "Akil", "Baca", 
        "Bokobá", "Buctzotz", "Cacalchén", "Calotmul", 
        "Cansahcab", "Cantamayec", "Celestún", "Cenotillo", 
        "Chacsinkín", "Chankom", "Chapab", "Chemax", 
        "Chichimilá", "Chicxulub Pueblo", "Chikindzonot", "Chocholá", 
        "Chumayel", "Conkal", "Cuncunul", "Cuzamá", 
        "Dzán", "Dzemul", "Dzidzantún", "Dzilam de Bravo", 
        "Dzilam González", "Dzitás", "Dzoncauich", "Espita", 
        "Halachó", "Hocabá", "Hoctún", "Homún", 
        "Huhí", "Hunucmá", "Ixil", "Izamal", 
        "Kanasín", "Kantunil", "Kaua", "Kinchil", 
        "Kopomá", "Mama", "Maní", "Maxcanú", 
        "Mayapán", "Mérida", "Mocochá", "Motul", 
        "Muna", "Muxupip", "Opichén", "Oxkutzcab", 
        "Panabá", "Peto", "Progreso", "Quintana Roo", 
        "Río Lagartos", "Sacalum", "Samahil", "Sanahcat", 
        "San Felipe", "Santa Elena", "Seyé", "Sinanché", 
        "Sotuta", "Sucilá", "Sudzal", "Suma", 
        "Tahdziú", "Tahmek", "Teabo", "Tecoh", 
        "Tekal de Venegas", "Tekantó", "Tekax", "Tekit", 
        "Tekom", "Telchac Pueblo", "Telchac Puerto", "Temax", 
        "Temozón", "Tepakán", "Tetiz", "Teya", 
        "Ticul", "Timucuy", "Tinum", "Tixcacalcupul", 
        "Tixkokob", "Tixméhuac", "Tixpéhual", "Tizimín", 
        "Tunkás", "Tzucacab", "Uayma", "Ucú", 
        "Umán", "Valladolid", "Xocchel", "Yaxcabá", 
        "Yaxkukul", "Yobaín"
    ],
    "Zacatecas": [
        "Apozol", "Apulco", "Atolinga", "Benito Juárez", 
        "Calera", "Cañitas de Felipe Pescador", "Chalchihuites", "Concepción del Oro", 
        "Cuauhtémoc", "El Plateado de Joaquín Amaro", "El Salvador", "Fresnillo", 
        "Genaro Codina", "General Enrique Estrada", "General Francisco R. Murguía", "General Pánfilo Natera", 
        "Guadalupe", "Huanusco", "Jalpa", "Jerez", 
        "Jiménez del Teul", "Juan Aldama", "Juchipila", "Loreto", 
        "Luis Moya", "Mazapil", "Melchor Ocampo", "Mezquital del Oro", 
        "Miguel Auza", "Momax", "Monte Escobedo", "Morelos", 
        "Moyahua de Estrada", "Nochistlán de Mejía", "Noria de Ángeles", "Ojocaliente", 
        "Pánuco", "Pinos", "Río Grande", "Sain Alto", 
        "Santa María de la Paz", "Sombrerete", "Susticacán", "Tabasco", 
        "Tepechitlán", "Tepetongo", "Teúl de González Ortega", "Tlaltenango de Sánchez Román", 
        "Trancoso", "Trinidad García de la Cadena", "Valparaíso", "Vetagrande", 
        "Villa de Cos", "Villa García", "Villa González Ortega", "Villa Hidalgo", 
        "Villanueva", "Zacatecas"
    ],
    "Puebla": [
    "Acajete", "Acateno", "Acatlán", "Acatzingo", 
    "Acteopan", "Ahuacatlán", "Ahuatlán", "Ahuazotepec", 
    "Ahuehuetitla", "Ajalpan", "Albino Zertuche", "Aljojuca", 
    "Altepexi", "Amixtlán", "Amozoc", "Aquixtla", 
    "Atempan", "Atexcal", "Atlequizayan", "Atlixco", 
    "Atoyatempan", "Atzala", "Atzitzihuacán", "Atzitzintla", 
    "Axutla", "Ayotoxco de Guerrero", "Calpan", "Caltepec", 
    "Camocuautla", "Caxhuacan", "Chalchicomula de Sesma", "Chapulco", 
    "Chiautla", "Chiautzingo", "Chiconcuautla", "Chichiquila", 
    "Chietla", "Chigmecatitlán", "Chignahuapan", "Chignautla", 
    "Chila", "Chila de la Sal", "Chilchotla", "Chinantla", 
    "Coatepec", "Coatzingo", "Cohetzala", "Cohuecan", 
    "Coronango", "Coxcatlán", "Coyomeapan", "Coyotepec", 
    "Cuapiaxtla de Madero", "Cuautempan", "Cuautinchán", "Cuautlancingo", 
    "Cuayuca de Andrade", "Cuetzalan del Progreso", "Cuyoaco", "Domingo Arenas", 
    "Eloxochitlán", "Epatlán", "Esperanza", "Francisco Z. Mena", 
    "General Felipe Ángeles", "Guadalupe", "Guadalupe Victoria", "Hermenegildo Galeana", 
    "Honey", "Huachinango", "Huaquechula", "Huatlatlauca", 
    "Huauchinango", "Huehuetla", "Huehuetlán el Chico", "Huehuetlán el Grande", 
    "Huejotzingo", "Hueyapan", "Hueytamalco", "Hueytlalpan", 
    "Huitzilan de Serdán", "Huitziltepec", "Ixcamilpa de Guerrero", "Ixcaquixtla", 
    "Ixtacamaxtitlán", "Ixtepec", "Izúcar de Matamoros", "Jalpan", 
    "Jolalpan", "Jonotla", "Jopala", "Juan C. Bonilla", 
    "Juan Galindo", "Juan N. Méndez", "La Magdalena Tlatlauquitepec", "Lafragua", 
    "Libres", "Los Reyes de Juárez", "Mazapiltepec de Juárez", "Mixtla", 
    "Molcaxac", "Naupan", "Nauzontla", "Nealtican", 
    "Nicolás Bravo", "Nopalucan", "Ocotepec", "Ocoyucan", 
    "Olintla", "Oriental", "Pahuatlán", "Palmar de Bravo", 
    "Pantepec", "Petlalcingo", "Piaxtla", "Puebla", 
    "Quecholac", "Quimixtlán", "Rafael Lara Grajales", "San Andrés Cholula", 
    "San Antonio Cañada", "San Diego la Mesa Tochimiltzingo", "San Felipe Teotlalcingo", "San Felipe Tepatlán", 
    "San Gabriel Chilac", "San Gregorio Atzompa", "San Jerónimo Tecuanipan", "San Jerónimo Xayacatlán", 
    "San José Chiapa", "San José Miahuatlán", "San Juan Atenco", "San Juan Atzompa", 
    "San Martín Texmelucan", "San Martín Totoltepec", "San Matías Tlalancaleca", "San Miguel Ixitlán", 
    "San Miguel Xoxtla", "San Nicolás Buenos Aires", "San Nicolás de los Ranchos", "San Pablo Anicano", 
    "San Pedro Cholula", "San Pedro Yeloixtlahuaca", "San Salvador el Seco", "San Salvador el Verde", 
    "San Salvador Huixcolotla", "San Sebastián Tlacotepec", "Santa Catarina Tlaltempan", "Santa Inés Ahuatempan", 
    "Santa Isabel Cholula", "Santiago Miahuatlán", "Santo Tomás Hueyotlipan", "Soltepec", 
    "Tecali de Herrera", "Tecamachalco", "Tecomatlán", "Tehuacán", 
    "Tehuitzingo", "Tenampulco", "Teopantlán", "Teotlalco", 
    "Tepanco de López", "Tepango de Rodríguez", "Tepatlaxco de Hidalgo", "Tepeaca", 
    "Tepemaxalco", "Tepeojuma", "Tepetzintla", "Tepexco", 
    "Tepexi de Rodríguez", "Tepeyahualco", "Tepeyahualco de Cuauhtémoc", "Tetela de Ocampo", 
    "Teteles de Ávila Castillo", "Teziutlán", "Tianguismanalco", "Tilapa", 
    "Tlachichuca", "Tlacotepec de Benito Juárez", "Tlacuilotepec", "Tlahuapan", 
    "Tlaltenango", "Tlanepantla", "Tlaola", "Tlapacoya", 
    "Tlapanalá", "Tlatlauquitepec", "Tlaxco", "Tochimilco", 
    "Tochtepec", "Totoltepec de Guerrero", "Tulcingo", "Tuzamapan de Galeana", 
    "Tzicatlacoyan", "Venustiano Carranza", "Vicente Guerrero", "Xayacatlán de Bravo", 
    "Xicotepec", "Xicotlán", "Xiutetelco", "Xochiapulco", 
    "Xochiltepec", "Xochitlán de Vicente Suárez", "Xochitlán Todos Santos", "Yaonáhuac", 
    "Yehualtepec", "Zacapala", "Zacapoaxtla", "Zacatlán", 
    "Zapotitlán", "Zapotitlán de Méndez", "Zaragoza", "Zautla", 
    "Zihuateutla", "Zinacatepec", "Zongozotla", "Zoquiapan", 
    "Zoquitlán"
]
        };

    export const seedEstadosYMunicipios = async () => {
    try {
        const existing = await EstadosYMunicipios.countDocuments();
        if (existing === 0) {
        const inserts = Object.entries(estadosYMunicipiosData).map(([estado, municipios]) => ({
            estado,
            municipios
        }));
        await EstadosYMunicipios.insertMany(inserts);
        console.log('🌎 Estados y municipios insertados correctamente.');
        } else {
        console.log('✔️ Ya existen estados y municipios en la base de datos.');
        }
    } catch (error) {
        console.error('❌ Error insertando estados y municipios:', error.message);
    }
    };
